spring:
  application:
    name: bell-mock
server:
  port: 8082
  address: 0.0.0.0
management:
  endpoints:
    web:
      exposure:
        include: "*"
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
    tags:
      application: ${spring.application.name}
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true